<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.9.1.1 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 9484 2006-10-03 13:11:22Z nijel $
 * Date: Wed, 20 Dec 2006 23:43:56 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:vsepulve) [1] */
$i++;
$cfg['blowfish_secret'] = 'zidingirnngienekanpa';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['controluser'] = 'buscador';
$cfg['Servers'][$i]['controlpass'] = 'buscador';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'buscador';
$cfg['Servers'][$i]['password'] = 'buscador';
//$cfg['Servers'][$i]['only_db'] = 'control_panel';

/* End of servers configuration */

?>
